<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'StartDate' => [parent::class, 'StartDate', null],
        "\0".parent::class."\0".'endDate' => [parent::class, 'endDate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'img' => [parent::class, 'img', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'pillars' => [parent::class, 'pillars', null],
        "\0".parent::class."\0".'quotes' => [parent::class, 'quotes', null],
        'StartDate' => [parent::class, 'StartDate', null],
        'endDate' => [parent::class, 'endDate', null],
        'id' => [parent::class, 'id', null],
        'img' => [parent::class, 'img', null],
        'name' => [parent::class, 'name', null],
        'pillars' => [parent::class, 'pillars', null],
        'quotes' => [parent::class, 'quotes', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
