<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMKwGUm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMKwGUm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMKwGUm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMKwGUm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTMKwGUm\App_KernelDevDebugContainer([
    'container.build_hash' => 'TMKwGUm',
    'container.build_id' => '86e5131f',
    'container.build_time' => 1707476124,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMKwGUm');
