<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAzhdTPj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAzhdTPj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAzhdTPj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAzhdTPj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAzhdTPj\App_KernelDevDebugContainer([
    'container.build_hash' => 'AzhdTPj',
    'container.build_id' => 'efd4886c',
    'container.build_time' => 1707777322,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAzhdTPj');
