<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTS9xf1c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTS9xf1c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTS9xf1c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTS9xf1c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTS9xf1c\App_KernelDevDebugContainer([
    'container.build_hash' => 'TS9xf1c',
    'container.build_id' => '2b5d9ff1',
    'container.build_time' => 1707475719,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTS9xf1c');
