<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.0d623935.js',
                '/build/926.5544cd75.js',
                '/build/app.a6349f12.js',
            ],
            'css' => [
                '/build/app.9348f80d.css',
            ],
        ],
    ],
],

]];
